tests/reaim: 'die' if cannot cd into executive folder
Signed-off-by: Oliver Sang <oliver.sang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/reaim b/tests/reaim
--- a/tests/reaim
+++ b/tests/reaim
@@ -45,7 +45,7 @@ run_for_iterations()
 	run_reaim $iterations
 }
 
-cd $BENCHMARK_ROOT/reaim || exit
+cd $BENCHMARK_ROOT/reaim || die "fail to cd $BENCHMARK_ROOT/reaim"
 
 if [ -z "$nr_task" ]; then
 	REAIM_STARTUSERS=1
