tests/schbench: make it possible to set intervaltime
Intervaltime is used to determine how often schbench print current
latency stats and the printed stats can affect stat/schbench calculating
latency average and stddev.

When some large runtime value is used, the purpose is to have the
workload itself to stablize and deliver some stable latency values for
the entire $runtime time. But if every 10s(default interval) a latency
stat is printed, that can affect stat/schbench to see too many changing
values and that can affect schbench's stddev.

Make it possible to specify intervaltime so users who don't want to see
many latency stats can set intervaltime to be the same as runtime to get
a single latency stat at the end of the test.

Signed-off-by: Aaron Lu <aaron.lu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/schbench b/tests/schbench
--- a/tests/schbench
+++ b/tests/schbench
@@ -5,6 +5,7 @@
 # - sleeptime_us
 # - cputime_us
 # - iterations
+# - intervaltime_s
 
 . $LKP_SRC/lib/reproduce-log.sh
 
@@ -24,9 +25,11 @@ cd $BENCHMARK_ROOT/schbench || die "no $BENCHMARK_ROOT/schbench"
 
 [ $message_threads -eq 0 ] && message_threads=2
 
+[ -n "$intervaltime_s" ] && interval_opt="-i $intervaltime_s"
+
 # the source code print the output to stderr, here redirection stderr to stdout
 for i in $(seq $iterations)
 do
 	echo Iteration : $i
-	log_cmd ./schbench -m $message_threads -t $worker_threads -r $runtime -s $sleeptime_us -c $cputime_us 2>&1 || die "Schbench run failed"
+	log_cmd ./schbench -m $message_threads -t $worker_threads -r $runtime -s $sleeptime_us -c $cputime_us $interval_opt 2>&1 || die "Schbench run failed"
 done
