programs/schbench: remove obsolete options
sleeptime and cputime options have been removed from schbench

d0fbd83 schbench: get rid of the sleep time parameter
91ea787 schbench: get rid of the usec_spin based think time

Signed-off-by: Yujie Liu <yujie.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/programs/schbench/run b/programs/schbench/run
--- a/programs/schbench/run
+++ b/programs/schbench/run
@@ -2,8 +2,6 @@
 # - message_threads
 # - worker_threads
 # - runtime
-# - sleeptime_us
-# - cputime_us
 # - iterations
 # - intervaltime_s
 
@@ -13,8 +11,6 @@ cd $BENCHMARK_ROOT/schbench || die "no $BENCHMARK_ROOT/schbench"
 
 : [ -n "$worker_threads" ] || worker_threads=16
 : [ -n "$runtime" ] || runtime=300
-: "${sleeptime_us:=30000}"
-: "${cputime_us:=30000}"
 
 # to avoid "core dumped", set message_threads to default 2 if message_threads
 # is 0 because message_threads is used as denominator in schbench command.
@@ -31,5 +27,5 @@ cd $BENCHMARK_ROOT/schbench || die "no $BENCHMARK_ROOT/schbench"
 for i in $(seq $iterations)
 do
 	echo Iteration : $i
-	log_cmd ./schbench -m $message_threads -t $worker_threads -r $runtime -s $sleeptime_us -c $cputime_us $interval_opt 2>&1 || die "Schbench run failed"
+	log_cmd ./schbench -m $message_threads -t $worker_threads -r $runtime $interval_opt 2>&1 || die "Schbench run failed"
 done
