programs/kbuild/run: explicitly set time format
Print the time in pure second style to facilitate parsing.

== example ==

$ { TIMEFORMAT=$'\nreal: %Rs\nuser: %Us\nsys: %Ss'; time { make defconfig &> /dev/null; }; } 2>&
1

real: 3.141s
user: 2.072s
sys: 1.120s

Fixes: 97ba7e4bcbe6 ("programs/kbuild/run: time the make process")
Signed-off-by: Yujie Liu <yujie.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/programs/kbuild/run b/programs/kbuild/run
--- a/programs/kbuild/run
+++ b/programs/kbuild/run
@@ -45,7 +45,7 @@ run_kbuild()
 		log_cmd scripts/config --file .config --enable CONFIG_TRIM_UNUSED_KSYMS
 
 		echo "start time: $(date +%s.%N)"
-		{ time make -j $parallel $target > /dev/null; } 2>&1 || die "make -j $parallel $target failed"
+		{ TIMEFORMAT=$'\nreal: %Rs\nuser: %Us\nsys: %Ss'; time { make -j $parallel $target &> /dev/null; }; } 2>&1 || die "make -j $parallel $target failed"
 		echo "end time: $(date +%s.%N)"
 		iterations=$((iterations + 1))
 		now=$(date +%s)
