programs/kbuild/run: time the make process
The default output of "time" command is stderr. Need to quote it with
braces to redirect it to stdout.

Link: https://github.com/intel/lkp-tests/issues/229
Signed-off-by: Yujie Liu <yujie.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/programs/kbuild/run b/programs/kbuild/run
--- a/programs/kbuild/run
+++ b/programs/kbuild/run
@@ -45,7 +45,7 @@ run_kbuild()
 		log_cmd scripts/config --file .config --enable CONFIG_TRIM_UNUSED_KSYMS
 
 		echo "start time: $(date +%s.%N)"
-		log_cmd make -j $parallel $target > /dev/null 2>&1 || die "make -j $parallel $target failed"
+		{ time make -j $parallel $target > /dev/null; } 2>&1 || die "make -j $parallel $target failed"
 		echo "end time: $(date +%s.%N)"
 		iterations=$((iterations + 1))
 		now=$(date +%s)
