programs/perf-fuzzer/run: resolve exit failure
The test can run and terminated earlier

        Overflows: 6  Recursive: 0
        SIGIOs due to RT signal queue full: 0
	*** buffer overflow detected ***: terminated
	Aborted

	/lkp/lkp/src/programs/perf-fuzzer/run: 44: kill: No such process

which results in the last state as below

	test.perf-fuzzer.exit_code.1: 1
	exit_fail: 1

Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/programs/perf-fuzzer/run b/programs/perf-fuzzer/run
--- a/programs/perf-fuzzer/run
+++ b/programs/perf-fuzzer/run
@@ -35,13 +35,26 @@ echo "glibc version $(ldd --version | head -1)"
 # Run test
 opt="-r $seed"
 [ -n "$number" ] && opt="$opt -s $number"
-log_cmd ./perf_fuzzer $opt &
 
 # Wait test finish or timeout
-pid=$!
 if [ -n "$runtime" ]; then
-	sleep "$runtime"
-	kill -9 "$pid" 2>&1
+	log_cmd timeout $runtime ./perf_fuzzer $opt
+	exit_status=$?
+
+	if [ $exit_status -eq 124 ]; then
+		echo "perf fuzzer test is timeout"
+		exit $exit_status
+	else
+		echo "perf fuzzer test exits with status $exit_status"
+		# It's expected that fuzzer exits with fail status like 134 due to
+		#	buffer overflow detected ***: terminated
+		# The exit_fail in last_state doesn't mean much (like trigger a valuable
+		# bisection), so always exit 0 if fuzzer exits itself.
+		exit 0
+	fi
 else
+	log_cmd ./perf_fuzzer $opt &
+	pid=$!
+
 	wait "$pid" 2>&1
 fi
