programs/ltp/pkg/PKGBUILD: detect inconsistent syscalls standalone tests
the test name and param may change overtime in ltp source code. add some
code to detect if the standalone test is inconsistent with the entry in
syscalls file.

Signed-off-by: Yujie Liu <yujie.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/programs/ltp/pkg/PKGBUILD b/programs/ltp/pkg/PKGBUILD
--- a/programs/ltp/pkg/PKGBUILD
+++ b/programs/ltp/pkg/PKGBUILD
@@ -123,7 +123,7 @@ install_numactl()
 
 build()
 {
-	split_syscalls_tests
+	split_syscalls_tests || return
 
 	cd $srcdir/$pkgname || return
 
@@ -159,6 +159,10 @@ split_syscalls_tests()
 	standalone_file=$LKP_SRC/pkg/${pkgname}/addon/tests/standalone
 	while read line
 	do
+		grep -q "^$line$" syscalls || {
+			echo "standalone test \"$line\" is not found in syscalls"
+			return 1
+		}
 		echo $line > ./"${line//[[:blank:]]/.}"
 	done < <(cat $standalone_file | grep -v '^#')
 
